development:
  adapter: async

test:
  adapter: test

production:
  adapter: redis
  url: redis://redistogo:c0d8c4b4da3876a898d8b4c21b2817a9@spinyfin.redistogo.com:9979/
  channel_prefix: backend_production
