development:
  adapter: async

test:
  adapter: test

production:
  adapter: redis
  url: redis://redistogo:82f16510385075024e8d48658f885e1a@scat.redistogo.com:10674/
  channel_prefix: backend_production
